In [3]:
import numpy as np
import time

In [4]:
arrays = np.array([1,2,3,4,5])
print(arrays,type(arrays))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [5]:
size = 100_00_000

#python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time {end - start} sec")

#numpy array
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr ** 2
end = time.time()
print(f"python list time {end - start} sec")

python list time 0.6041116714477539 sec
python list time 0.02504277229309082 sec


In [6]:
import sys

print(f"python list size = {sys.getsizeof(py_list)* len(py_list)} bytes")

print(f"numpy array size = {np_arr.nbytes} bytes")

python list size = 800000560000000 bytes
numpy array size = 80000000 bytes


In [7]:
#Create - from lists
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2, type(arr2),arr2.shape)

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D, type(arr2D), arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> (3, 3)


In [8]:
#Create
arr1 = np.zeros((2,3), dtype = "int64") #prefill
print(arr1, arr1.shape)

arr2 = np.ones((5,)) 
print(arr2, arr2.shape)

arr3 = np.full((3,4), 100) #prefill with value
print(arr3, arr3.shape)

arr4 = np.eye((3)) #identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(0, 11, 2) #range elements
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 3) #evenly spaced arrays
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.   50.5 100. ] (3,)


In [9]:
#Properties
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape) #dimensions = m x n
print(arr.size)  #size 9
print(arr.dtype)
print(arr.ndim) 

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [10]:
#Operations on arrays 

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr, arr.shape)

reshaped = arr.reshape((5,2))
print(reshaped, reshaped.shape)

flattened = arr.flatten()
print(flattened, flattened.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] (2, 5)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] (5, 2)
[ 1  2  3  4  5  6  7  8  9 10] (10,)


In [11]:
#Indexing
arr = np.array([3,56,7,324,5,98])
print(arr[5])

new2D = np.array([[32,43,65,63],[23,54,7,234],[35,86,897,64]])
print(new2D[0],[3])
print(new2D[2][3])

#Fancy indexing
arr = np.array([43,54,7,34,5,43])
index = [1,3,5]
print(arr[index])

#Boolean indexing
print(arr[arr > 2]) #nums greater than 2
print(arr[arr % 2 == 0]) #even nums
print(arr[arr % 2 != 0])

98
[32 43 65 63] [3]
64
[54 34 43]
[43 54  7 34  5 43]
[54 34]
[43  7  5 43]


In [12]:
# Slicing
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[2:6]) #[3, 4, 5, 6]
print(arr[:6]) #[1, 2, 3, 4, 5, 6]
print(arr[3:]) #[4, 5, 6, 7]
print(arr[::2]) #[1, 3, 5, 7]

[3 4 5 6]
[1 2 3 4 5 6]
[4 5 6 7]
[1 3 5 7]


In [15]:
#Copy vs View by slicing
#Sliced list is a copy
py_list = [1,2,3,4,5]
copy_list = py_list[1:4]
copy_list[1] = 333

print(copy_list)
print(py_list)

#Sliced array is a viwe
np_arr = np.array([1,2,3,4,5])
viwe_arr = np_arr[1:4]
viwe_arr[1] = 333

print(viwe_arr)
print(np_arr)

#Creating a copy
copy_arr = np_arr[1:4].copy()
copy_arr[2] = 444
print(copy_arr)
print(np_arr)

[2, 333, 4]
[1, 2, 3, 4, 5]
[  2 333   4]
[  1   2 333   4   5]
[  2 333 444]
[  1   2 333   4   5]
